title: Blog Assassin's Creed
default_lang: fr
author:
  name: Benjamin Pilliez
  email: benjamin.pilliez@sfr.fr
metadata:
  description: "Création d'un blog avec le CMS GRAV"

# Header customization
header:
  title: Assassin's Creed.
  description: <p>Un petit blog sur les épisodes d'Assassin's Creed </a>.
copyright:
  - line: © Copyright  Pilliez Benjamin
social:
  - url: "https://www.facebook.com/benjamin.pilliez?ref=bookmarks"
    icon: facebook
  - url: "https://www.linkedin.com/in/benjamin-pilliez-bb0624175/"
    icon: linkedin
  - url : "https://github.com/BenPilliez"
    icon: github

