title: Portfolio pour tester GRAV
default_lang: fr
author:
  name: Benjamin Pilliez
  email: benjamin.pilliez@sfr.fr
metadata:
  description: "Création d'un blog avec le CMS GRAV"

# Header customization
header:
  title: Assassin's Creed.
  description: <p>Un petit blog sur les épisodes d'Assassin's Creed </a>.
copyright:
  - line:
  - line:


